language: java
jdk: oraclejdk8
install: true

sudo: false # faster builds

script: mvn clean install
script: "mvn cobertura:cobertura"
mvn test -B
after_success:
  - bash <(curl -s https://codecov.io/bash)
