language: java
jdk: oraclejdk8
install: true

sudo: false # faster builds

before_script:
  - echo "MAVEN_OPTS='-Dheadless=true'" > ~/.mavenrc
script:
  - mvn clean install
  - mvn cobertura:cobertura
  - mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
